### ISSUE TITLE
Customize.yaml includes a location

### ISSUE THREAD

**Issue by alco28** [bafplus/HA-afvalinfo-card#1]
In de customize.yaml komt een verwijzing voor in de sensor naam waarin ook de opgegeven locatie zit. in uw voorbeeld is dat 'thuis'. echter als je dat niet in je afvalinfo configuratie gebruikt (of een andere) dan werkt de customize verwijzing helemaal niet. voorbeeldje: `sensor.afvalinfo_**thuis_**gft:`

Ook is het tegenstrijdig met het voorbeeld uit de configuration.yaml waarin staat dat het ID: Thuis ook weggelaten zou mogen worden.

Oplossing is lijkt mij even het vermelden in de readme en standaard geen locaties te geven aan de afvalinfo. immers de meeste gebruikers zullen het maar inzetten voor alleen thuis gebruik.

**Comment by alco28** [comment]
je hebt het wel staan in de readme.md maar voorbeeldje zou het misschien verduidelijken.

**Comment by bafplus** [comment]
Ik heb het gehele ID gedeelte uit de config en de voorbeelden gehaald.

Alle sensoren heten nu sensor.afvalinfo_gft (bijvoorbeeld) by default.
