### ISSUE TITLE
Afvalinfo card No icons and fault while changing the configuration.yaml

### ISSUE THREAD

**Issue by Raspyguy** [bafplus/HA-afvalinfo-card#11]
Hi Bafplus,
i'am setting up the Afvalinfo card but have some problems with it.
following your guide, so.....
having installed the integration and fill in the form with no problems.
then placed the configuration.yaml file into my configuration.yaml but the i have some faults. so where should i place this file.

also i have no icons which are in the www/images/
can you help me out with this
thanks in advance

**Comment by bafplus** [comment]
The afvalinfo integration has gotten a new version (v2) that breaks the current guides in this repo.
I will try to update this repo as soon as p[ossible.

With this new version there is no need to place anything into the configuration.yaml.
After you have installed the afvalinfo integration into HACS, restart HA and go to integrations and add the afvalinfo integration. It will ask you for some details like your postcode etc. You can also follow the guide as described in the afvalinfo repo: https://github.com/heyajohnny/afvalinfo

You can find all icons in this repo in the "icons" folder.
Just upload all these icons into your /www/images/ forlder in HA.

Hope this helps :-)

**Comment by Raspyguy** [comment]
Hi,
Thanks for your fast reply 
So that means that it's only needed to install the integration and fill in the postcode and huisnummer?
I have done that but, when creating a card the dates are correct but i' am not seeing the icons for the waste. Only the mdi:recycle is displayed!
Any idea?

**Comment by bafplus** [comment]
Correct, just add afvalinfo using HACS, go to settings->integrations and add Afvalinfo.
Then fill in the form with your zipcode, housenumber and city.

Regarding the images, de names of the sensors are changed with the V2 update.
It now includes the name you give in the first option diring install ("home" by default).
That makes it very hard to include all and every possible sensor :-)

What you need to do is make sure that every sensorname (just try with 1 first until it works) corresponds to the actual sensor names you now have in your system.

If you raly cant make it work you may always PM me on facebook or something so i can help you out.

**Comment by Raspyguy** [comment]
Hello again,
Sorry but it isn' t working.
What do you mean with,

What you need to do is make sure that every sensorname (just try with 1 first until it works) corresponds to the actual sensor names you now have in your system.

When i look at the sensorname, this is the as in the system.
Sorry but whats the easy way to help me out. Do not have a Facebook account so 🤐

**Comment by bafplus** [comment]
Double check that each sensorname is exactly the same, like the GFT example in these images.
![Screenshot 2023-12-19 21 27 21](https://github.com/bafplus/HA-afvalinfo-card/assets/6432986/2ce2e601-aaa6-4ab9-b94d-0193035809de)
![Screenshot 2023-12-19 21 26 42](https://github.com/bafplus/HA-afvalinfo-card/assets/6432986/b422a81d-0f36-4293-aa36-0182eaac39b1)

**Comment by bafplus** [comment]
Also make sure you have this at the top of your configuration.yaml:

```
homeassistant:
  customize: !include customize.yaml
```
  
  Else Home Assistant does not "see" your costomize.yaml :-)
  
![Screenshot 2023-12-19 21 33 55](https://github.com/bafplus/HA-afvalinfo-card/assets/6432986/751f1c00-dfda-46fe-940b-bbfcc66c1e19)
Dont forget to restart HA for all this to take effect.

**Comment by Raspyguy** [comment]
Hi there,
Finally it's solved👍 
Reason.......i created the folder "costomize.yaml" instead of
"customize.yaml" so 🤐😬
Sorry for this stupid mistake but, many thanks for your help.
Merry Christmas/Prettige kerstdagen
Regards/groeten

**Comment by bafplus** [comment]
Ah yeah, a file works better in this case :-)

Happy hollidays en een voorspoedig 2024!

Op do 21 dec 2023 om 14:11 schreef Raspyguy ***@***.***>:
