### ISSUE TITLE
I can't find the content of customize.yaml

### ISSUE THREAD

**Issue by papabak** [bafplus/HA-afvalinfo-card#13]

**Comment by bafplus** [comment]
Its in the root: https://github.com/bafplus/HA-afvalinfo-card/blob/main/customize.yaml

**Comment by papabak** [comment]
Thank you. Found it!
Dirk
________________________________
Van: bafplus ***@***.***>
Verzonden: Thursday, February 1, 2024 5:42:08 PM
Aan: bafplus/HA-afvalinfo-card ***@***.***>
CC: papabak ***@***.***>; Author ***@***.***>
Onderwerp: Re: [bafplus/HA-afvalinfo-card] I can't find the content of customize.yaml (Issue #13)


Its in the root: https://github.com/bafplus/HA-afvalinfo-card/blob/main/customize.yaml
