### ISSUE TITLE
typo link address: ReadMe documents section Afbeeldingen, iconen en naam sensoren point 2

### ISSUE THREAD

**Issue by jmlk52** [bafplus/HA-afvalinfo-card#15]
ReadMe documents section Afbeeldingen, iconen en naam sensoren point 2,
typo:
      clicking Link customize.yaml results in:
            404 - page not found
      The main branch of HA-afvalinfo-card does not contain the path costumize.yaml.

incorrect (typo):
https://github.com/bafplus/HA-afvalinfo-card/blob/main/**costumize**.yaml

Must be:
https://github.com/bafplus/HA-afvalinfo-card/blob/main/customize.yaml

**Comment by bafplus** [comment]
fixed, thanks!
