### ISSUE TITLE
automatiseringen/melding-tts.yaml proper language

### ISSUE THREAD

**Issue by jmlk52** [bafplus/HA-afvalinfo-card#16]
Might be depending of another global configuration setting elsewhere, but as per current melding-tts.yaml setting I had to add language: "nl" after message body to get the Dutch pronouncation. 
See:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.woonkamer #de entiteit van het apparaat wat de melding uit moet spreken
      message: "Morgen wordt het afval opgehaald. Zet de {{states.sensor.afvalinfo_home_trash_type_tomorrow.state}} buiten."
      language: "nl"
mode: single

**Comment by bafplus** [comment]
That indeed depends on what TTS integration one uses. It is optional tho, cause you can set the language on a system wide setting in the config of the TTS integration. But this also works :-)
