### ISSUE TITLE
Custom element not found: auto-entities

### ISSUE THREAD

**Issue by ElProempie** [bafplus/HA-afvalinfo-card#4]
Wanneer ik de content van `afvalkalender.yaml` in een kaart plak, krijg ik de volgende foutmelding:

`Configuratiefouten ontdekt: Custom element not found: auto-entities`

Als ik de kaart Sensor toevoeg, werkt alles naar behoren. Dus dan maar zo. 
Ik wou het wel even aangeven. Wellicht dat ik iets fout heb gedaan. 

Verder heb je een onwijs fijne guide voor de leken onder ons!

**Comment by bafplus** [comment]
Excuus voor de late reactie :-)

Dan ben je waarschijnlijk vergeten om de auto-entities integratie te installeren. Zie laatste stap in de readme.

Mochten er dan nog problemen zijn laat dan even een reactie hieronder achter.
