### ISSUE TITLE
Krijg geen data

### ISSUE THREAD

**Issue by Koal4** [bafplus/HA-afvalinfo-card#5]
Hi,

Krijg geen data maar zie ook niks van logging.
Nu zie ik wel een grote waarschuwing 'LET OP! Door laatste update is het een en ander veranderd. Alle code in de repo is al aangepast maar door gebrek aan tijd zijn de readme's nog niet hierop aangepast!' dus wellicht heeft het daarmee te maken. 

Maar wat is er veranderd? Misschien iets meer details mbt de term 'een en ander' dan kan ik zelf op speurtocht gaan ;) en is deze melding wel relevant? Ik weet nu niet hoelang dit er al op staat en misschien nooit is weggehaald. Een datum zou wel handig zijn.

Ik ben namelijk de boel aan het migreren naar een nieuwe kale installatie dus ben alles met de hand aan passen/maken. Op de oude installatie zie ik ook overal unknown en via 'dev' kom ik alleen de sensors tegen die ik al in gebruik had (dus geen andere). Tegen het einde van het jaar had ik wel vaker unknowns maar dat lag dan aan de leverancier (in dit geval RD4/Heerlen). Dus ja beetje verwarrende situatie waar ik nu in zit..

gr

**Comment by bafplus** [comment]
Excuus voor de late reactie :-)

Even los van het weergeven van de data in de cards zouden de sensoren wel gewoon data moeten bevatten.
Krijg je geen data binnen, check dan even op https://4fv4l.nl/ of het daar wel werkt. Komt daar wel data naar boven dan werkt de integratie wel naar behoren, maar zal er waarschijnlijk iets niet goed gaan in je config.yaml.

Als er nogsteeds problemen zijn laat dan even een berichtje hieronder achter.
