### ISSUE TITLE
Geen icons

### ISSUE THREAD

**Issue by keeskor** [bafplus/HA-afvalinfo-card#6]

**Comment by keeskor** [comment]
Ik krijg niet de Nieuwe icons te zien. Ik heb de map images aangemaakt onder www en ik heb. de volgende regel toegevoegd aan mij configuration.yaml. 
homeassistant:
  customize: !include customize.yaml
Ik heb ook de customize.yaml gevuld

**Comment by Dust-E** [comment]
Hi @keeskor, 
Ik zie dat je dit ticket gesloten hebt, heb je dit zelf kunnen oplossen, zo ja hoe?

**Comment by keeskor** [comment]
Ja klopt.

Vriendelijk groet,
C. Korzelius

Op 3 jan. 2023 om 15:05 heeft Dust-E ***@***.***> het volgende geschreven:

﻿

Hi @keeskor<https://github.com/keeskor>,
Ik zie dat je dit ticket gesloten hebt, heb je dit zelf kunnen oplossen, zo ja hoe?

**Comment by Dust-E** [comment]
kan je ook aangeven hoe je het opgelost hebt?
bvd

**Comment by keeskor** [comment]
Ik had de inhoud van customize.yaml 1 op 1 gekopieerd en niet sensor namen aangepast. Nadat ik de juiste sensor namen had ingevuld werkte het netjes.

Vriendelijk groet,
C. Korzelius

Op 4 jan. 2023 om 19:02 heeft Dust-E ***@***.***> het volgende geschreven:

﻿

kan je ook aangeven hoe je het opgelost hebt?
bvd
