### ISSUE TITLE
Geen icons

### ISSUE THREAD

**Issue by HesselKoopmans** [bafplus/HA-afvalinfo-card#7]
Na het invullen van alle benodigde informatie blijven mijn icons niet bestaand/wit. De files staan wel netjes in de www/images. ook de sensor namen kloppen

**Comment by Alphaxed** [comment]
Bestel Hessel en bafplus, ook ik heb dit probleem. 
De customize.yaml staat zoals het lijkt ook goed in de configuration.yaml

Iemand een tip?

**Comment by HesselKoopmans** [comment]
Bij mij zijn de icons ineens spontaan tevoorschijn gekomen, ik heb eigenlijk geen idee waardoor. Misschien heeft ie ff tijd nodig :)

**Comment by Fliha** [comment]
<img width="509" alt="Scherm­afbeelding 2023-03-09 om 17 41 26" src="https://user-images.githubusercontent.com/107475529/224092104-47eeb5ad-753b-4d55-8010-4ee20d093320.png">
Krijg alleen het icoon voor oud papier te zien, die van gft en restafval krijg ik niet te zien. Heb alles meerdere keren gecontroleerd maar kan de fout niet vinden. 

#hesselkoopmans Hoe lang heb je er op moeten wachten? Ben nu al een paar dagen verder, geen iconen waar ik ze verwacht

Vind het raar dat die van papier wel zichtbaar is

Ook hier wordt een tip zeer gewaardeerd 😊

**Comment by Fliha** [comment]
<img width="539" alt="Scherm­afbeelding 2023-03-09 om 18 27 05" src="https://user-images.githubusercontent.com/107475529/224107285-8948b5c4-93b6-4d0c-94bc-c88c82a9bb06.png">
Heb mijn fout gevonden, 

In customize.yaml was de friendly_name niet gelijk aan de conifiguration.yaml. 
Heb de namen in beide (customize.yaml en configuration.yaml) veranderd naar grijze container en groene container, en gelijk werden de iconen zichtbaar. 

Mijn uitleg zal waarschijnlijk knullig overkomen maar het heeft voor mij gewerkt
