### ISSUE TITLE
Automation not working as expected

### ISSUE THREAD

**Issue by abctje** [bafplus/HA-afvalinfo-card#8]
I've implemented afvalinfo and the notification script. I try to achieve that it sends a message the night before garbage is collected with the correct garbage info. It works but not 100% I get a notification every night at the specified time, even when there is nothing to report. This is to much ;-)

Is this something I've implemented wrong or is this the nature of the beast?

Here is my automation yaml:

alias: Afvalmelding
description: Melding dag voor afval
trigger:
  - platform: time
    at: "21:00"
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.afvalinfo_afval_voor_morgen
        state: none
action:
  - service: notify.prowlbericht
    data:
      message: "Afval morgen: {{states.sensor.afvalinfo_afval_voor_morgen.state}}"
      title: Afval morgen, container naar de weg!
mode: single

**Comment by abctje** [comment]
Never mind, I figured it out! Had to RTFM ;-)

**Comment by PuckStar** [comment]
Can you tell me what you changed?
I have the same issue.
Already checked that the name of the sensor is correct.

As state is shows "geen" but regardless if I test with "geen" or "none" as the NOT condition.
It still does the action everyday, so on a day without pickup it says "zet geen aan de weg".
