### ISSUE TITLE
Afvalinfo on mobile devices not shown

### ISSUE THREAD

**Issue by ArnoS57** [bafplus/HA-afvalinfo-card#9]
I installed Afvalinfo as suggested on your page.
I made a card which is show on my computer.
![Foto 22-10-2023 om 14 37](https://github.com/bafplus/HA-afvalinfo-card/assets/87931108/dcc07f95-bc87-411b-8dfb-e76948f3e33f)

On my moblie devices I get an errormessage.
![IMG_4857](https://github.com/bafplus/HA-afvalinfo-card/assets/87931108/78124334-3be6-4ee7-acba-2b3105fc002f)

How to correct this?

**Comment by bafplus** [comment]
Should work fine.
Try to empty the cache and reload the page.

Op zo 22 okt. 2023 14:51 schreef Arno ***@***.***>:

**Comment by ArnoS57** [comment]
I forgot to say the error occures in the HA app on the mobile devices.
When I open a browser and go to HA local it works fine.

Met vriendelijke groet, Arno Sormani Verzonden via mijn Ipad/Iphone


Op zo 22 okt 2023 om 16:04 schreef bafplus ***@***.***>

**Comment by ArnoS57** [comment]
What happend I don’t know. It works fine now.
Before my earlier message I also cleared the cache and there was still an
error.
10 min. later opened the HA app again and everything is OK.
Thanks anyway for the support.


Met vriendelijke groet, Arno Sormani Verzonden via mijn Ipad/Iphone


Op zo 22 okt 2023 om 17:03 schreef Arno Sormani ***@***.***>
